# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lab2.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(798, 516)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 781, 471))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.openGLWidget = QtWidgets.QOpenGLWidget(self.horizontalLayoutWidget)
        self.openGLWidget.setObjectName("openGLWidget")
        self.horizontalLayout.addWidget(self.openGLWidget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_7.addWidget(self.label_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.useScissor = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.useScissor.setObjectName("useScissor")
        self.horizontalLayout_3.addWidget(self.useScissor)
        self.useBlend = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.useBlend.setObjectName("useBlend")
        self.horizontalLayout_3.addWidget(self.useBlend)
        self.useAlpha = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.useAlpha.setObjectName("useAlpha")
        self.horizontalLayout_3.addWidget(self.useAlpha)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.verticalLayout_7)
        self.line = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_6.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.scissor_x = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.scissor_x.setObjectName("scissor_x")
        self.verticalLayout_2.addWidget(self.scissor_x)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.scissor_y = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.scissor_y.setObjectName("scissor_y")
        self.verticalLayout_2.addWidget(self.scissor_y)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.scissor_w = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.scissor_w.setObjectName("scissor_w")
        self.verticalLayout_6.addWidget(self.scissor_w)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.scissor_h = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.scissor_h.setObjectName("scissor_h")
        self.verticalLayout_6.addWidget(self.scissor_h)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.line_2 = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.alpha_func = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.alpha_func.setObjectName("alpha_func")
        self.horizontalLayout_5.addWidget(self.alpha_func)
        self.alpha_ref = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget)
        self.alpha_ref.setObjectName("alpha_ref")
        self.horizontalLayout_5.addWidget(self.alpha_ref)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.line_3 = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.blend_sfactor = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.blend_sfactor.setObjectName("blend_sfactor")
        self.verticalLayout_8.addWidget(self.blend_sfactor)
        self.blend_dfactor = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.blend_dfactor.setObjectName("blend_dfactor")
        self.verticalLayout_8.addWidget(self.blend_dfactor)
        self.verticalLayout.addLayout(self.verticalLayout_8)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 798, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "Choose test"))
        self.useScissor.setText(_translate("MainWindow", "Scissor"))
        self.useBlend.setText(_translate("MainWindow", "Blend"))
        self.useAlpha.setText(_translate("MainWindow", "Alpha"))
        self.label_6.setText(_translate("MainWindow", "Scissor"))
        self.label.setText(_translate("MainWindow", "X:"))
        self.label_2.setText(_translate("MainWindow", "Y:"))
        self.label_3.setText(_translate("MainWindow", "width"))
        self.label_4.setText(_translate("MainWindow", "height"))
        self.label_7.setText(_translate("MainWindow", "Alpha"))
        self.label_8.setText(_translate("MainWindow", "Blend"))


