from OpenGL.GL import *
from OpenGL.GLU import *
from OpenGL.GLUT import *

PRIMITIVES = {
    'GL_POINTS': GL_POINTS,
    'GL_LINES': GL_LINES,
    'GL_LINE_STRIP': GL_LINE_STRIP, 
    'GL_LINE_LOOP': GL_LINE_LOOP,
    'GL_TRIANGLES': GL_TRIANGLES,
    'GL_TRIANGLE_STRIP': GL_TRIANGLE_STRIP, 
    'GL_TRIANGLE_FAN': GL_TRIANGLE_FAN,
    'GL_QUADS': GL_QUADS,
    'GL_QUAD_STRIP': GL_QUAD_STRIP,
    'GL_POLYGON': GL_POLYGON,
}

TRANSPARENCY = {
    'GL_ALWAYS': GL_ALWAYS,
    'GL_NEVER': GL_NEVER,
    'GL_LESS': GL_LESS,
    'GL_EQUAL': GL_EQUAL,
    'GL_LEQUAL': GL_LEQUAL,
    'GL_GREATER': GL_GREATER,
    'GL_NOTEQUAL': GL_NOTEQUAL,
    'GL_GEQUAL': GL_GEQUAL,
    'GL_NEVER': GL_NEVER
}

SFACTOR = {
    'GL_ONE': GL_ONE,
    'GL_ZERO': GL_ZERO,
    'GL_DST_COLOR': GL_DST_COLOR,
    'GL_ONE_MINUS_DST_COLOR': GL_ONE_MINUS_DST_COLOR,
    'GL_SRC_ALPHA': GL_SRC_ALPHA,
    'GL_ONE_MINUS_SRC_ALPHA': GL_ONE_MINUS_SRC_ALPHA,
    'GL_DST_ALPHA': GL_DST_ALPHA,
    'GL_ONE_MINUS_DST_ALPHA': GL_ONE_MINUS_DST_ALPHA,
    'GL_SRC_ALPHA_SATURATE': GL_SRC_ALPHA_SATURATE
}

DFACTOR = {
    'GL_ZERO': GL_ZERO,
    'GL_ONE': GL_ONE,
    'GL_SRC_COLOR': GL_SRC_COLOR,
    'GL_ONE_MINUS_SRC_COLOR': GL_ONE_MINUS_SRC_COLOR,
    'GL_SRC_ALPHA': GL_SRC_ALPHA,
    'GL_ONE_MINUS_SRC_ALPHA': GL_ONE_MINUS_SRC_ALPHA,
    'GL_DST_ALPHA': GL_DST_ALPHA,
    'GL_ONE_MINUS_DST_ALPHA': GL_ONE_MINUS_DST_ALPHA
}